In [1]:
import pandas as pd

In [10]:
df = pd.DataFrame({
    'col1' : [1,2,3,4,5],
    'col2' : [10,20,30,40,50],
    'col3' : "one two three four five".split()
})

In [11]:
# Create col4 with square of col1 values
df

col1  col2   col3
0     1    10    one
1     2    20    two
2     3    30  three
3     4    40   four
4     5    50   five

In [12]:
df['col4'] = df['col1']**2

In [13]:
df

col1  col2   col3  col4
0     1    10    one     1
1     2    20    two     4
2     3    30  three     9
3     4    40   four    16
4     5    50   five    25

In [14]:
df['col5'] = df['col3'].str[0]
df

col1  col2   col3  col4 col5
0     1    10    one     1    o
1     2    20    two     4    t
2     3    30  three     9    t
3     4    40   four    16    f
4     5    50   five    25    f

In [17]:
def sqrFunc(a) :
    return a**2

In [19]:
df['col4_4'] = df['col1'].apply(sqrFunc)
df

col1  col2   col3  col4 col5  col4_4
0     1    10    one     1    o       1
1     2    20    two     4    t       4
2     3    30  three     9    t       9
3     4    40   four    16    f      16
4     5    50   five    25    f      25

In [20]:
def condFunc(a) :
    if a == 't' :
        return 't'
    else :
        return 'z'

In [21]:
df['col6'] = df['col5'].apply(condFunc)
df

col1  col2   col3  col4 col5  col4_4 col6
0     1    10    one     1    o       1    z
1     2    20    two     4    t       4    t
2     3    30  three     9    t       9    t
3     4    40   four    16    f      16    z
4     5    50   five    25    f      25    z

In [22]:
# Try with lambda function
df['col6_6'] = df['col5'].apply(lambda a : 't' if a == 't' else 'z')
df

col1  col2   col3  col4 col5  col4_4 col6 col6_6
0     1    10    one     1    o       1    z      z
1     2    20    two     4    t       4    t      t
2     3    30  three     9    t       9    t      t
3     4    40   four    16    f      16    z      z
4     5    50   five    25    f      25    z      z

In [23]:
# Create col7 to hold length of string in col3
df['col7'] = df['col3'].apply(len)
df

col1  col2   col3  col4 col5  col4_4 col6 col6_6  col7
0     1    10    one     1    o       1    z      z     3
1     2    20    two     4    t       4    t      t     3
2     3    30  three     9    t       9    t      t     5
3     4    40   four    16    f      16    z      z     4
4     5    50   five    25    f      25    z      z     4

In [28]:
import math
df['col8'] = df['col2'].apply(math.log)
df

col1  col2   col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    10    one     1    o       1    z      z     3  2.302585
1     2    20    two     4    t       4    t      t     3  2.995732
2     3    30  three     9    t       9    t      t     5  3.401197
3     4    40   four    16    f      16    z      z     4  3.688879
4     5    50   five    25    f      25    z      z     4  3.912023

In [29]:
import numpy as np

In [32]:
l = ["manu", 1,2,3,4]
type(l)

list

In [33]:
np.array(l)

array(['manu', '1', '2', '3', '4'], dtype='<U11')

In [34]:
type(np.array(l)) # Result : ndarray - n-dimentional array

numpy.ndarray

In [41]:
a1 =np.array([3,4,5,6,4.5]) # because of 1 float value, in result all values were up-casted to float
a1

array([3. , 4. , 5. , 6. , 4.5])

In [37]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [38]:
# How to get value 4 from above
a[1,1]

4

In [39]:
a[1][1]

4

In [42]:
a1

array([3. , 4. , 5. , 6. , 4.5])

In [43]:
np.array([1,2,3,4], ndmin = 0)

array([1, 2, 3, 4])

In [44]:
np.array([1,2,3,4], ndmin = 1)

array([1, 2, 3, 4])

In [45]:
np.array([1,2,3,4], ndmin = 4)

array([[[[1, 2, 3, 4]]]])

In [46]:
a2 = np.array([1,2,3,4], ndmin = 4)

In [47]:
a2[0]

array([[[1, 2, 3, 4]]])

In [48]:
a2[0][0]

array([[1, 2, 3, 4]])

In [49]:
a2[0][0][0]

array([1, 2, 3, 4])

In [50]:
a2[0][0][0][0]

1

In [ ]:
a = [1, 2, 3, 4, 5]

In [56]:
np.asarray(a)

array([[1, 2],
       [3, 4]])

In [57]:
np.asanyarray(a)

array([[1, 2],
       [3, 4]])

In [54]:
np.mat([1,2,3,4,5]) # matrix

matrix([[1, 2, 3, 4, 5]])

In [58]:
np.asanyarray(np.mat(a))

matrix([[1, 2],
        [3, 4]])

In [59]:
# Matrix is subclass of array

In [60]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [61]:
    np.fromfunction(lambda i, j : i*j , (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [62]:
 np.fromfunction(lambda i, j, k : i*j*k , (3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.]],

       [[0., 0.],
        [0., 2.],
        [0., 4.]]])

In [65]:
 np.fromfunction(lambda i, j, k, l : i*j*k*l , (4,3,2,2), dtype = int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [67]:
a = np.fromfunction(lambda i, j, k : i*j*k , (4,3,2), dtype = int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [68]:
a.ndim # How many dimention

3

In [69]:
a.size # How many elements

24

In [70]:
a.shape

(4, 3, 2)

In [71]:
a.dtype

dtype('int32')

In [72]:
df = pd.DataFrame(a) # a is 3d while DataFrame takes only 2d
# So convert it to 2d using reshape()

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [81]:
a.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [82]:
a.reshape(12,2) # so we can reshape 4,3,2 to 12,2 OR 6,4 OR any combination with 24

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [84]:
df = pd.DataFrame(a.reshape(8,3))
df

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [85]:
a.reshape(4,2,1,3) # Can be used to convert data into any shape/dimention

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [86]:
a.reshape(4,-1) # -1 means, it will autofill -1 with the other required dimension to make it 24 here.i.e. 4 rows and 6 cols


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [87]:
a.reshape(2,4,-234) # -1 is not necessary. Any negative number works

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [73]:
np.random.rand(100, 4) # Random values in a shape, here 100 rows - 4 cols

array([[0.89705292, 0.62024061, 0.40676071, 0.36285064],
       [0.47296415, 0.92740862, 0.60718514, 0.9078175 ],
       [0.70382918, 0.52283878, 0.64810409, 0.55927116],
       [0.56571633, 0.18173956, 0.58567437, 0.20270432],
       [0.00984536, 0.12796762, 0.72676714, 0.0625221 ],
       [0.32798115, 0.14078368, 0.35115309, 0.78459666],
       [0.29771216, 0.3521595 , 0.03458126, 0.31237947],
       [0.49967761, 0.64289394, 0.66903055, 0.48072918],
       [0.07018691, 0.29330301, 0.35691776, 0.84499554],
       [0.25916088, 0.09802354, 0.97666324, 0.88310055],
       [0.20310918, 0.50519522, 0.41841908, 0.62305214],
       [0.46403607, 0.66458348, 0.12771045, 0.63469662],
       [0.7501271 , 0.89003133, 0.04582812, 0.78219416],
       [0.48231691, 0.80849195, 0.62964069, 0.89251707],
       [0.0105562 , 0.92405835, 0.07118262, 0.20394428],
       [0.90428527, 0.88377637, 0.18405716, 0.88244671],
       [0.61348963, 0.56645738, 0.18753087, 0.87763326],
       [0.87744976, 0.34670399,

In [78]:
np.random.randint(4,50) # Any random number between given values

46

In [79]:
np.random.randn(4,5) # Try to generate a normal distribution

array([[ 1.12553864, -1.6067936 , -1.05780746, -0.21534789,  1.92948454],
       [-0.30788803,  1.11884744, -0.57579674, -0.08972666, -0.9585845 ],
       [ 0.90642471,  1.24086497,  1.13949399,  0.80333049,  0.92708106],
       [-0.91136432,  0.08676234,  0.03189343, -0.57759184, -1.14375884]])

In [80]:
df = pd.DataFrame(np.random.randn(4,5))
df

0         1         2         3         4
0 -0.508504 -0.654543 -0.370475 -0.840666  0.010260
1  1.293553  0.334667  2.014345  0.395709 -0.911687
2  0.970293  0.199466  1.287555  0.184987  1.952875
3  1.964513 -1.181157  1.493117  2.113215  0.295245

In [88]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [91]:
list(range(4,10,2))

[4, 6, 8]

In [92]:
# Lets see equivalent to range in numpy
np.arange(4,10,2)

array([4, 6, 8])

In [93]:
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [95]:
a1 = np.arange(4,10.5,0.2)
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [96]:
a1[1:4] # Slicing operation

array([4.2, 4.4, 4.6])

In [98]:
arr = np.random.rand(4,5)
arr

array([[0.10949358, 0.3032467 , 0.60707333, 0.76126216, 0.98288107],
       [0.58825947, 0.82060377, 0.18790166, 0.99856946, 0.94304405],
       [0.10309476, 0.14623233, 0.78153535, 0.84899119, 0.88708902],
       [0.97396873, 0.9413501 , 0.73122318, 0.21703982, 0.51334615]])

In [99]:
# Extract all data greater than 0.5
arr > 0.5

array([[False, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [False, False,  True,  True,  True],
       [ True,  True,  True, False,  True]])

In [100]:
arr[arr > 0.5]

array([0.60707333, 0.76126216, 0.98288107, 0.58825947, 0.82060377,
       0.99856946, 0.94304405, 0.78153535, 0.84899119, 0.88708902,
       0.97396873, 0.9413501 , 0.73122318, 0.51334615])

In [101]:
arr

array([[0.10949358, 0.3032467 , 0.60707333, 0.76126216, 0.98288107],
       [0.58825947, 0.82060377, 0.18790166, 0.99856946, 0.94304405],
       [0.10309476, 0.14623233, 0.78153535, 0.84899119, 0.88708902],
       [0.97396873, 0.9413501 , 0.73122318, 0.21703982, 0.51334615]])

In [103]:
# Fetch items at indexes 2-1 and 2-2
arr[[1,2], [2]]

array([0.18790166, 0.78153535])

In [104]:
arr = np.random.rand(8,5)
arr

array([[0.96990453, 0.71758381, 0.80322175, 0.30305611, 0.51841881],
       [0.1450336 , 0.76218086, 0.52063883, 0.39079459, 0.23933716],
       [0.42826267, 0.8966376 , 0.9903408 , 0.29897421, 0.0484414 ],
       [0.91566875, 0.07094679, 0.4045683 , 0.52432886, 0.1210663 ],
       [0.06168584, 0.36379218, 0.53264813, 0.41753052, 0.18423503],
       [0.10381748, 0.65751195, 0.32152124, 0.3847981 , 0.86882597],
       [0.26881997, 0.4909165 , 0.86554421, 0.35695957, 0.99935114],
       [0.5293916 , 0.32962254, 0.10316598, 0.66777989, 0.86029364]])

In [106]:
arr[1:8,0:3]

array([[0.1450336 , 0.76218086, 0.52063883],
       [0.42826267, 0.8966376 , 0.9903408 ],
       [0.91566875, 0.07094679, 0.4045683 ],
       [0.06168584, 0.36379218, 0.53264813],
       [0.10381748, 0.65751195, 0.32152124],
       [0.26881997, 0.4909165 , 0.86554421],
       [0.5293916 , 0.32962254, 0.10316598]])

In [108]:
a2 = arr[1:8,[0,1,2]]
a2

array([[0.1450336 , 0.76218086, 0.52063883],
       [0.42826267, 0.8966376 , 0.9903408 ],
       [0.91566875, 0.07094679, 0.4045683 ],
       [0.06168584, 0.36379218, 0.53264813],
       [0.10381748, 0.65751195, 0.32152124],
       [0.26881997, 0.4909165 , 0.86554421],
       [0.5293916 , 0.32962254, 0.10316598]])

In [111]:
a2[0][0] = 10
a2

array([[10.        ,  0.76218086,  0.52063883],
       [ 0.42826267,  0.8966376 ,  0.9903408 ],
       [ 0.91566875,  0.07094679,  0.4045683 ],
       [ 0.06168584,  0.36379218,  0.53264813],
       [ 0.10381748,  0.65751195,  0.32152124],
       [ 0.26881997,  0.4909165 ,  0.86554421],
       [ 0.5293916 ,  0.32962254,  0.10316598]])

In [112]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [113]:
a

array([[1, 2],
       [3, 4]])

In [114]:
b

array([[2, 3],
       [4, 5]])

In [115]:
# Element wise multiplication
a*b

array([[ 2,  6],
       [12, 20]])

In [119]:
# Matrix Multiplication
# Rule 1 - First's column should be equal to others row count
m = a@b # @ is for matrix multiplication
m

array([[10, 13],
       [22, 29]])

In [120]:
m/0 # Look at result carefully. Resultant array is with inf values. inf - infinity

C:\Users\Manu\AppData\Local\Temp/ipykernel_22704/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])