In [1]:
# NumPy stands for Numerical Python and is the core library for numeric and scientific computing

In [2]:
# Single dimantional array
import numpy as np

n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [5]:
# Multi-dimentional array

n2 = np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [6]:
# More examples
l1 = [1,2,3,4]
n1 = np.array(l1)
n1

array([1, 2, 3, 4])

In [7]:
type(n1)

numpy.ndarray

In [12]:
n2 = np.array([[1,2,3],[4,5,6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# Initializing Numpy array with zeros

import numpy as np
n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [15]:
n2 = np.zeros((4,6))
n2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
# Initializing numpy arry with same number

n1 = np.full((2,3), 5)
n1

array([[5, 5, 5],
       [5, 5, 5]])

In [18]:
# Initializing numpy arry within a range

n1 = np.arange(10,20) # As usual, from(included) - to(excluded)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
n1 = np.arange(10,31,5) # a range with a step
n1

array([10, 15, 20, 25, 30])

In [23]:
# Initializing numpy arry with random numbers

n1 = np.random.randint(100,200,10)
n1

array([133, 124, 199, 186, 128, 102, 126, 185, 187, 139])

In [ ]:
# Checking the shape of numpy arrays

In [25]:
n1 = np.array([[1,2,3,4],[4,3,2,1]])
n1

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [27]:
n1.shape

(2, 4)

In [28]:
n1.shape = (4,2)
n1

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [29]:
n1.shape = (3,5)
n1

ValueError: cannot reshape array of size 8 into shape (3,5)

In [35]:
# Joining Numpy Arrays - vstack(), hstack(), column_stack()

n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [33]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
# Numpy Intersection & Difference

n1 = np.array([1,2,3,4,5,6,7])
n2 = np.array([6,7,8,9])

np.intersect1d(n1,n2) # Intersection / common values between two arrays

array([6, 7])

In [37]:
np.setdiff1d(n1,n2) # Provide elements from first array, not shared with 2nd array

array([1, 2, 3, 4, 5])

In [38]:
np.setdiff1d(n2,n1) # Provide elements from first array, not shared with 2nd array

array([8, 9])

In [39]:
# Numpy Array Mathematics

# Addition
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

np.sum([n1,n2])

21

In [40]:
np.sum([n1,n2], axis=0)

array([5, 7, 9])

In [41]:
np.sum([n1,n2], axis=1)

array([ 6, 15])

In [42]:
# Basic Addition
n1 = np.array([1,2,3])

n1 = n1+1
n1

array([2, 3, 4])

In [43]:
# Basic Multiplication

n1 = n1*3
n1

array([3, 6, 9])

In [44]:
# Basic Subtraction

n1 = n1 - 2
n1

array([-1,  0,  1])

In [47]:
# Basic Division

n1 = n1 / 2
n1

array([0.5, 1. , 1.5])

In [49]:
# Numpy Math Functions

n1 = np.array([1,2,3,4,5,6,7,8])
# Mean
np.mean(n1)

4.5

In [50]:
# Standard Deviation

n1 = np.array([1,5,3,100,4,48])
np.std(n1)

36.59424666377065

In [56]:
# Median

n1 = np.array([1,55,32.8,100,4,48])
np.median(n1)

40.4

In [58]:
# Numpy Save & Load

n1 = np.array([1,2,3,4,5,6])
np.save('my_numpy', n1)  # Saving Numpy Array
n2 = np.load("my_numpy.npy")  # Loading Numpy Array
n2

array([1, 2, 3, 4, 5, 6])